[package]
name = "neptune-rpc-client"
description = "library for interacting with neptune-cash's JSON-RPC"
authors = ["Triton Software"]
version = "0.4.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.24", default-features = false, features = ["json", "default-tls", "system-proxy"] }
serde_json = "1.0"
neptune-cash = { path = "../../neptune-core" }
async-trait = "0.1.83"

[dev-dependencies]
tokio = { version = "1.41", features = ["full", "tracing"] }

[lints]
workspace = true
